default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'hexlet_app2_test' %>
  username: <%= ENV['DB_USERNAME'] || 'pguser' %>
  password: <%= ENV['DB_PASSWORD'] || 'pgpassword' %>
  host: <%= ENV['DB_HOST'] || 'localhost' unless ENV['GITHUB_ACTIONS'].nil? %>
  port: <%= ENV['DB_PORT'] || 5432 unless ENV['GITHUB_ACTIONS'].nil? %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  