default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hexlet_app2_development
  username: pguser
  password: pgpassword

test:
  <<: *default
  pool: 10
  database: hexlet_app2_test
  username: <%= ENV['DB_USERNAME'] || 'pguser' %>
  password: <%= ENV['DB_PASSWORD'] || 'pgpassword' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  