name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U pguser -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpassword
          POSTGRES_DB: hexlet_app2_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Test database connection
        run: |
          pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USERNAME
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: pguser
          DB_PASSWORD: pgpassword

      - name: Ensure database exists
        run: |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U postgres -c "CREATE DATABASE hexlet_app2_test;"
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U postgres -c "CREATE USER pguser WITH PASSWORD 'pgpassword';"
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE hexlet_app2_test TO pguser;"
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: pgpassword

      - name: Prepare test database
        run: make prepare_test_db
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: pguser
          DB_PASSWORD: pgpassword

      - name: Run tests
        run: make test
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: pguser
          DB_PASSWORD: pgpassword