name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U pguser -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpassword
          POSTGRES_DB: hexlet_app2_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U pguser; do
            echo "Waiting for Postgres...";
            sleep 1;
          done

      - name: Prepare test database
        run: make prepare_test_db
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: pguser
          DB_PASSWORD: pgpassword

      - name: Run tests
        run: make test
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: pguser
          DB_PASSWORD: pgpassword
